http:
  routers:
    opnsense-rtr:                                                                                                                                               # Adjust the router name (e.g. [HOSTNAME]-rtr)
      rule: 'Host(`opnsense.{{env "TRAEFIK_DOMAIN"}}`)'                                                                                                         # Adjust the [HOSTNAME]
      # entryPoints:                                                                                                                                            # Optional: Use an entryPoint other than the default
      #   - websecure
      # middlewares:                                                                                                                                            # Optional: Add specific middlewares to this router
      #   - middleware@file
      service: opnsense-svc                                                                                                                                     # Adjust the service name (e.g. [HOSTNAME]-svc)
      # tls:                                                                                                                                                    # Optional: Add specific tls options to this router
      #   certResolver: cloudflare
  services:
    opnsense-svc:                                                                                                                                               # Adjust the service name to match the service name above
      loadBalancer:
        servers:
          - url: "https://192.168.20.1:31337/"                                                                                                                  # Adjust the url to your application
          - url: "https://192.168.10.1:31337/"                                                                                                                  # Adjust the url to your application