---
services:
  authentik-worker:
    #######################################################################
    # --- CONTAINER BASICS
    #######################################################################
    image: ${IMAGE:?Image required}
    container_name: ${TRAEFIK_HOSTNAME:?Hostname required}-worker
    hostname: ${TRAEFIK_HOSTNAME}-worker
    restart: unless-stopped                                                                                                                                     # Automatically restart unless manually stopped
    # build:                                                                                                                                                    # Optional: build image from local Dockerfile
    #   context: .
    #   dockerfile: Dockerfile

    #######################################################################
    # --- SECURITY SETTINGS
    #######################################################################
    user: '0:0'                                                                                                                                                 # Optional: run as specific non-root user (app user)
    read_only: true                                                                                                                                             # Filesystem is read-only except for mounted volumes
    cap_drop:                                                                                                                                                   # Drop all capabilities by default
      - ALL
    cap_add:                                                                                                                                                    # Add needed capabilities
      - SETUID                                                                                                                                                  # Set user ID
      - SETGID                                                                                                                                                  # Set group ID
      - CHOWN                                                                                                                                                   # Change file ownership
      - FOWNER                                                                                                                                                  # Bypass permission checks on files you own
    security_opt:
      - no-new-privileges:true                                                                                                                                  # Prevent privilege escalation

    #######################################################################
    # --- SYSTEM RUNTIME
    #######################################################################
    init: true                                                                                                                                                  # PID 1 is tini – handles zombies properly
    stop_grace_period: 30s                                                                                                                                      # Give app time to shut down gracefully
    oom_score_adj: -500                                                                                                                                         # Reduce likelihood of getting killed under memory pressure
    tmpfs:                                                                                                                                                      # Ephemeral storage in RAM, auto-cleared on restart
      - /run                                                                                                                                                    # Mount /run as tmpfs for runtime files (PID files, sockets, etc.)
      - /tmp                                                                                                                                                    # Mount /tmp as tmpfs for temporary files; faster and auto-cleared on restart

    #######################################################################
    # --- FILESYSTEM & SECRETS
    #######################################################################
    volumes: *authentik_common_volumes                                                                                                                          # Mount external storage or host directories into the container for persistent data or config
    secrets: *authentik_common_secrets                                                                                                                          # Mount the defined secret into the container (usually under /run/secrets/)                                                                                                                                                  # Mount the defined secret into the container (usually under /run/secrets/)

    #######################################################################
    # --- NETWORKING / REVERSE PROXY
    #######################################################################
    # labels:                                                                                                                                                   # Metadata for the container, often used for service discovery or reverse proxy rules (e.g., Traefik)
    #   - "traefik.enable=true"                                                                                                                                 # Enable Traefik reverse proxy routing for this container
    #   - "traefik.http.routers.${TRAEFIK_HOSTNAME}-rtr.rule=Host(`${TRAEFIK_HOSTNAME}.${TRAEFIK_DOMAIN:?Domain required}`)"                                    # FQDN
    #   - "traefik.http.services.${TRAEFIK_HOSTNAME}-svc.loadBalancer.server.port=${TRAEFIK_PORT:?Port required}"                                               # Internal container port
    #   - "traefik.http.routers.${TRAEFIK_HOSTNAME}-rtr.middlewares=authentik-proxy@file"                                                                       # Optional Middlewares: Authentik proxy authentication
    # ports:                                                                                                                                                    # Optional: exposed ports
    #  - "9000:9000"
    #  - "9443:9443"
    # expose:                                                                                                                                                   # Optional: expose without publishing
    #  - "9000:9000"
    #  - "9443:9443"
    networks:                                                                                                                                                   # Define which Docker networks the container connects to (controls communication and isolation)
      - backend
      # - frontend
    # extra_hosts:                                                                                                                                              # Optional: manual host entries
    #   - "host.docker.internal:host-gateway"

    #######################################################################
    # --- RUNTIME / ENVIRONMENT
    #######################################################################
    command: ['worker']                                                                                                                                         # Override default container command
    # entrypoint: ['your-entrypoint.sh']                                                                                                                        # Override default container entrypoint
    environment: *authentik_common_environment                                                                                                                  # Environment variables for container configuration
    logging:                                                                                                                                                    # Configure log driver and limits to control log size and rotation
      driver: "json-file"
      options:
        max-size: "10m"                                                                                                                                         # Max log file size before rotation
        max-file: "3"                                                                                                                                           # Keep up to 3 rotated log files
    healthcheck:                                                                                                                                                # Periodic container health check to ensure service availability
      test: ["CMD", "ak", "healthcheck"]                                                                                                                        # Command to test container health
      interval: 30s                                                                                                                                             # Time between checks
      timeout: 5s                                                                                                                                               # Time to wait for response
      retries: 3                                                                                                                                                # Number of retries before marking unhealthy
      start_period: 10s                                                                                                                                         # Give the container time to initialize before health checks start
    stdin_open: false                                                                                                                                           # Optional: keep STDIN open
    tty: false                                                                                                                                                  # Disable terminal allocation; used for non-interactive containers

    #######################################################################
    # --- DEPENDENCIES
    #######################################################################
    depends_on:                                                                                                                                                 # Ensure these services are healthy before starting this one
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

    #######################################################################
    # --- SYSTEM LIMITS
    #######################################################################
    # shm_size: "256m"                                                                                                                                          # Shared memory (default 64M, useful e.g. for Chromium)
    # ulimits:                                                                                                                                                  # Set system resource limits for the container processes (Increasing nofile limits is useful for apps handling many simultaneous connections or files)
    #   nofile:                                                                                                                                                 # Controls the max number of open file descriptors (files, sockets, etc.)
    #     soft: 65535                                                                                                                                           # Soft limit: default max open files a process can have
    #     hard: 65535                                                                                                                                           # Hard limit: maximum value the soft limit can be raised to by privileged processes

# volumes:
#   data:
#     driver: local

secrets:                                                                                                                                                        # Define sensitive data (like passwords, tokens, keys) securely and inject into services at runtime
  POSTGRES_PASSWORD:
    file: ${POSTGRES_PASSWORD_PATH:?Secret Path required}${POSTGRES_PASSWORD_FILENAME:?Secret Filename required}                                                # Load secret from external file
  REDIS_PASSWORD:
    file: ${REDIS_PASSWORD_PATH:?Secret Path required}${REDIS_PASSWORD_FILENAME:?Secret Filename required}                                                      # Load secret from external file
  AUTHENTIK_SECRET_KEY_PASSWORD:
    file: ${AUTHENTIK_SECRET_KEY_PASSWORD_PATH:?Secret Path required}${AUTHENTIK_SECRET_KEY_PASSWORD_FILENAME:?Secret Filename required}                        # Load secret from external file

networks:
  # frontend:
  #   external: true
  backend:
    external: true