---
x-required-anchors:
  tmpfs: &mariadb_common_tmpfs
    - tmpfs
  secrets: &mariadb_common_secrets
    - secrets

services:
  mariadb_restore:
    ######################################################################
    # --- CONTAINER BASICS
    ######################################################################
    image: ${MARIADB_IMAGE:?Image required}
    container_name: ${APP_NAME:?App name required}-mariadb_restore
    hostname: ${APP_NAME}-mariadb_restore
    restart: no                                                                                                                                                 # Automatically restart unless manually stopped
    # build:                                                                                                                                                    # Optional: build image from local Dockerfile
    #   context: .
    #   dockerfile: Dockerfile

    ######################################################################
    # --- SECURITY SETTINGS
    ######################################################################
    user: '999:999'                                                                                                                                             # Optional: run as specific non-root user (app user)
    read_only: true                                                                                                                                             # Filesystem is read-only except for mounted volumes
    cap_drop:                                                                                                                                                   # Drop all capabilities by default
      - ALL
    cap_add:                                                                                                                                                    # Add needed capabilities
      - SETUID                                                                                                                                                  # Set user ID
      - SETGID                                                                                                                                                  # Set group ID
      - CHOWN                                                                                                                                                   # Change file ownership
    security_opt:
      - no-new-privileges:true                                                                                                                                  # Prevent privilege escalation

    ######################################################################
    # --- SYSTEM RUNTIME
    ######################################################################
    init: true                                                                                                                                                  # PID 1 is tini – handles zombies properly
    stop_grace_period: 30s                                                                                                                                      # Give app time to shut down gracefully
    oom_score_adj: -500                                                                                                                                         # Reduce likelihood of getting killed under memory pressure
    tmpfs: *mariadb_common_tmpfs                                                                                                                                # Ephemeral storage in RAM, auto-cleared on restart

    ######################################################################
    # --- FILESYSTEM & SECRETS
    ######################################################################
    volumes:                                                                                                                                                    # Mount external storage or host directories into the container for persistent data or config
      - /etc/localtime:/etc/localtime:ro                                                                                                                        # Set container time to host time
      - /etc/timezone:/etc/timezone:ro                                                                                                                          # Pass timezone info
      - database:/var/lib/mysql:rw                                                                                                                              # App data volume (adjust as needed)
      - ./scripts/restore-cron.sh:/scripts/restore-cron.sh:ro                                                                                                   # Script to do restore
      - ./restore:/restore                                                                                                                                      # Restore folder
    secrets: *mariadb_common_secrets                                                                                                                            # Mount the defined secret into the container (usually under /run/secrets/)

    ######################################################################
    # --- NETWORKING / REVERSE PROXY
    ######################################################################
    # labels:                                                                                                                                                   # Metadata for the container, often used for service discovery or reverse proxy rules (e.g., Traefik)
    #   - "traefik.enable=true"                                                                                                                                 # Enable Traefik reverse proxy routing for this container
    #   - "traefik.http.routers.${APP_NAME}-rtr.rule=${TRAEFIK_HOST}"                                                                                           # Traefik router
    #   - "traefik.http.services.${APP_NAME}-svc.loadBalancer.server.port=${TRAEFIK_PORT:?Port required}"                                                       # Internal container port
    #   - "traefik.http.routers.${APP_NAME}-rtr.middlewares=authentik-proxy@file"                                                                               # Optional Middlewares: Authentik proxy authentication
    # ports:                                                                                                                                                    # Optional: exposed ports
    #   - 8080:80
    # expose:                                                                                                                                                   # Optional: expose without publishing
    #   - 80
    networks:                                                                                                                                                   # Define which Docker networks the container connects to (controls communication and isolation)
      - backend
      # - frontend
    # extra_hosts:                                                                                                                                              # Optional: manual host entries
    #   - "host.docker.internal:host-gateway"

    ######################################################################
    # --- RUNTIME / ENVIRONMENT
    ######################################################################
    # command: ['your', 'default', 'command']                                                                                                                   # Override default container command
    entrypoint: ["sh", "-c", "/scripts/restore-cron.sh"]                                                                                                        # Override default container entrypoint
    environment:                                                                                                                                                # Environment variables for container configuration
      MYSQL_USER: ${APP_NAME}
      MYSQL_DATABASE: ${APP_NAME}
      MYSQL_AUTO_UPGRADE: true
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
      MYSQL_DB_HOST: ${APP_NAME}-mariadb
    logging:                                                                                                                                                    # Configure log driver and limits to control log size and rotation
      driver: "json-file"
      options:
        max-size: "10m"                                                                                                                                         # Max log file size before rotation
        max-file: "3"                                                                                                                                           # Keep up to 3 rotated log files
    healthcheck:                                                                                                                                                # Periodic container health check to ensure service availability
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']                                                                                      # Command to test container health
      interval: 30s                                                                                                                                             # Time between checks
      timeout: 5s                                                                                                                                               # Time to wait for response
      retries: 3                                                                                                                                                # Number of retries before marking unhealthy
      start_period: 10s                                                                                                                                         # Give the container time to initialize before health checks start
    stdin_open: false                                                                                                                                           # Optional: keep STDIN open
    tty: false                                                                                                                                                  # Disable terminal allocation; used for non-interactive containers

    ######################################################################
    # --- DEPENDENCIES
    ######################################################################
    depends_on:                                                                                                                                                 # Ensure these services are healthy before starting this one
      mariadb:
        condition: service_healthy

    ######################################################################
    # --- SYSTEM LIMITS
    ######################################################################
    # shm_size: "256m"                                                                                                                                          # Shared memory (default 64M, useful e.g. for Chromium)
    # ulimits:                                                                                                                                                  # Set system resource limits for the container processes (Increasing nofile limits is useful for apps handling many simultaneous connections or files)
    #   nofile:                                                                                                                                                 # Controls the max number of open file descriptors (files, sockets, etc.)
    #     soft: 65535                                                                                                                                           # Soft limit: default max open files a process can have
    #     hard: 65535                                                                                                                                           # Hard limit: maximum value the soft limit can be raised to by privileged processes

volumes:
  database:
    driver: local

secrets:                                                                                                                                                        # Define sensitive data (like passwords, tokens, keys) securely and inject into services at runtime
  MYSQL_PASSWORD:
    file: ${MYSQL_PASSWORD_PATH:?Secret Path required}${MYSQL_PASSWORD_FILENAME:?Secret Filename required}                                                      # Load secret from external file
  MYSQL_ROOT_PASSWORD:
    file: ${MYSQL_ROOT_PASSWORD_PATH:?Secret Path required}${MYSQL_ROOT_PASSWORD_FILENAME:?Secret Filename required}                                            # Load secret from external file

networks:
  # frontend:
  #   external: true
  backend:
    external: true